site_name: C Programming

nav:
  - Course Outline: index.md
  - Introduction:
      - Programming language:
          - Programming: programming.md
          - Overview of Computer Architecture: overview_of_CA.md
          - Introduction to Programming Language: programming_language.md
      - C Programming language:
          - Introduction to C: c_intro.md
          - Where C is Used: c_usage.md
          - Why Learn C: learn_c.md
  - Installation:
      - Visual Studio (VS) Code: vscode_installation.md
      - C/C++ Extention: c-cpp-extension.md
      - C Compiler: compiler_installation.md
      - Optional Extentions: optional-extensions.md
      - Testing your setup: testing_c_setup.md
  - Git and Github:
      - Version Control, Git and Github: version_control.md
      - Installation and setup:
        - Git and Github: install_git_github.md
        - Setup using ssh: setup_ssh_github.md
      - Starting a repository: starting_repository.md
      - Working with branch: working_with_branches.md
      - Undo changes: git-undoing-changes.md
      - Gitignore: gitignore.md
      - Fork: git_fork.md
  - Basic C Programming Concepts:
      - Statements: statements.md
      - Declarations: declarations.md
      - Comments: comments.md
      - Variables: variables.md
      - Input: inputs.md
      - Output: output.md
      - Escape sequences: escape_sequences.md
  - Operator and expression: operators_and_expressions.md
  - Control Structure:
      - Introduction: conditionals.md
      - Conditional Statements: conditional_statements.md
      - Loops: loop_control_statements.md
      - Loop Control Statements: loops.md
  - Assignments:
      - Assignment 1: assignment1.md
      - Assignment guide: assignment-guide.md

theme:
  name: material
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
  code:
    highlighting: true
    light: default
    dark: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences  
extra:
  generator: false
      
copyright: Copyright &copy; 2025 - Nirajan Thakuri
